### ISSUE TITLE
why `i         <- i + 1 ` is used before updating sample size?

### ISSUE THREAD

**Issue by lolofter** [godwinyung/npsurvSS#3]
https://github.com/godwinyyung/npsurvSS/blob/2c1ae85c76be243740c8f2d97d4cd4b4cca9d607/R/calc_power_and_sample_size.R#L264

Hi Godwin,

I am just curious why `i <- i + 1 ` is used before updating sample size? It makes more sense to me to update sample sizes first as `i` starts from 1. 

Thanks,
Jialuo

**Comment by godwinyyung** [comment]
Hi Jialuo,

Thank you for your question. It's been a while, but if I understand myself
correctly, it makes sense practically to start i from 2 because that is the
smallest possible number of person you might be able to split between two
arms. At the same time, you might not update the sample size at all, so on
line 268, you need to account for that scenario but shifting the index i.
In the end, there could be multiple ways to define initial i and to update
i, but all result in identical sample size calculation. I hope this helps.

Best,
Godwin
